# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

trigger:
- pipelines-codesign  # TEMPORARY

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'WWTExplorer3d\WWTExplorer.csproj'

- task: VSBuild@1
  inputs:
    solution: 'WWTExplorer3d\WWTExplorer.csproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: Build Explorer app

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
