# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

trigger:
- pipelines-codesign  # TEMPORARY

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'WWTExplorer.sln'

- task: VSBuild@1
  inputs:
    solution: 'WWTExplorer3d/WWTExplorer.csproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: Build Explorer app

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  inputs:
    solution: 'Setup1/Setup1.vdproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: Build installer
